name: 'kittygram'

services:
  kittygram_gateway:
    image: nginx:1.22.1
    container_name: gateway
    ports:
      - '80:80/tcp'
    restart: always
    depends_on:
      - kittygram_backend
      - kittygram_frontend
    networks:
      - kittygram-network
    volumes:
      - backend-static:/var/html/backend
      - media:/var/html/media
      - frontend-static:/var/html/static
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template

  kittygram_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    networks:
      - kittygram-network
    volumes:
      - backend-static:/app/collected_static
      - media:/app/media
    depends_on:
      - postgres
    
  kittygram_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    networks:
      - kittygram-network
    volumes:
      - frontend-static:/app/build
    
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: 'kittygram'
      POSTGRES_PASSWORD: 'kittygram'
      POSTGRES_DB: 'kittygram'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram-network

networks:
  kittygram-network:
    driver: bridge
  
volumes:
  pg_data:
  backend-static:
  media:
  frontend-static:
  